import type {
  InitialStateResponse,
  RegistryPresentation,
} from '../features/components/substrate/kernel/api/apiTypes'
import type { SceneWorld } from '../features/components/bridge/chassis/ambientScene/ambientSceneTypes'
import { TEST_RUNTIME_PRESENTATION } from './runtimePresentation.test.data'

export const TEST_AMBIENT_SCENE: SceneWorld = {
  ids: [
    'archive-orbit',
    'registry-spine',
    'pilgrim-transit',
    'relay-beacon',
    'terminus-horizon',
    'survey-monolith',
  ],
  positions: {
    'archive-orbit': { x: 68, y: 7, width: 34, height: 34, rotation: -14, depth: 1 },
    'registry-spine': { x: 5, y: 12, width: 7, height: 70, rotation: 0, depth: 2 },
    'pilgrim-transit': { x: 72, y: 73, width: 22, height: 2, rotation: -8, depth: 3 },
    'relay-beacon': { x: 89, y: 43, width: 2, height: 2, rotation: 0, depth: 4 },
    'terminus-horizon': { x: 10, y: 88, width: 80, height: 1, rotation: 0, depth: 1 },
    'survey-monolith': { x: 80, y: 18, width: 4, height: 22, rotation: 0, depth: 2 },
  },
  visuals: {
    'archive-orbit': { kind: 'orbit', priority: 'essential', label: 'Test orbit' },
    'registry-spine': { kind: 'spine', priority: 'essential', label: 'Test spine' },
    'pilgrim-transit': {
      kind: 'transit',
      priority: 'atmospheric',
      label: 'Test transit',
    },
    'relay-beacon': { kind: 'beacon', priority: 'atmospheric', label: 'Test beacon' },
    'terminus-horizon': { kind: 'horizon', priority: 'essential', label: 'Test horizon' },
    'survey-monolith': {
      kind: 'monolith',
      priority: 'atmospheric',
      label: 'Test monolith',
    },
  },
  motions: {
    'archive-orbit': { duration: 38, delay: 0, drift: 8 },
    'registry-spine': { duration: 18, delay: 2, drift: 2 },
    'pilgrim-transit': { duration: 14, delay: 4, drift: 18 },
    'relay-beacon': { duration: 5, delay: 1, drift: 0 },
    'terminus-horizon': { duration: 24, delay: 0, drift: 3 },
    'survey-monolith': { duration: 28, delay: 5, drift: 5 },
  },
}

export const TEST_INITIAL_STATE: InitialStateResponse & {
  readonly presentation: RegistryPresentation
} = {
  brandName: 'Test Brand',
  description: 'Test Description',
  iniTheme: 'light',
  registryCapabilities: [
    { id: '1', title: 'Test Feature', description: 'Test Feature Description' },
  ],
  operatingProtocols: [
    { id: '1', title: 'Test Procedure', description: 'Test Procedure Description' },
  ],
  themeCustom: { customThemeName: null },
  dossier: null,
  ambientScene: TEST_AMBIENT_SCENE,
  presentation: {
    metadata: {
      registryName: 'Test Registry',
      titleSuffix: ' — Test Owner',
      defaultDescription: 'Test default description',
      routes: {
        ingress: { title: 'Test Ingress', description: 'Test ingress description' },
        nexus: { title: 'Test Nexus', description: 'Test nexus description' },
        dossier: { title: 'Test Dossier', description: 'Test dossier description' },
        missions: { title: 'Test Missions', description: 'Test missions description' },
        telemetry: { title: 'Test Telemetry', description: 'Test telemetry description' },
        lostSignal: { title: 'Test missing', description: 'Test missing description' },
      },
    },
    ingress: {
      eyebrow: 'Test eyebrow',
      identityLabel: 'Test identity',
      name: 'Test Name',
      statement: 'Test statement',
      accessLabel: 'Test access',
      accessCountLabel: 'Test links',
      unitClass: 'Test class',
      ctas: [
        { href: '/missions', label: 'Test missions' },
        { href: '/dossier', label: 'Test dossier' },
        { href: '/telemetry', label: 'Test telemetry' },
      ],
      install: {
        webUrl: 'https://example.com',
        nativeUrl: null,
        webTitle: 'Test web title',
        webDescription: 'Test web description',
        nativeTitle: 'Test native title',
        nativeDescription: 'Test native description',
      },
    },
    nexus: {
      eyebrow: 'Test nexus eyebrow',
      headline: 'Test nexus headline',
      statement: 'Test nexus statement',
      presenceLabel: 'Test presence label',
      presences: [{ id: 'test', url: 'https://example.com', label: 'example.com' }],
    },
    missions: {
      eyebrow: 'Test mission eyebrow',
      headline: 'Test missions',
      statement: 'Test mission statement',
      loadingLabel: 'Test mission sync',
      errorLabel: 'Test mission unavailable',
      partialLabel: 'Test mission partial',
      partialDetail: 'Test mission retry',
      staleLabel: 'Test mission stale',
      staleDetail: 'Test mission reconnect',
      panels: {
        contributions: 'Test contribution panel',
        recorder: 'Test recorder panel',
        activity: 'Test activity panel',
        languages: 'Test languages panel',
      },
      metrics: {
        repositories: 'Test repositories',
        languages: 'Test languages',
        events: 'Test events',
        followers: 'Test followers',
      },
      copy: {
        activityKinds: {
          push: { singular: 'push', plural: 'pushes' },
          issue: { singular: 'issue', plural: 'issues' },
          pull_request: { singular: 'pull request', plural: 'pull requests' },
          issue_comment: { singular: 'issue comment', plural: 'issue comments' },
        },
        today: 'today',
        yesterday: 'yesterday',
        daysAgoUnit: 'days ago',
        monthsAgoUnit: 'months ago',
        yearsAgoUnit: 'years ago',
        changeKind: 'change',
        updatedPrefix: 'Updated',
        indexedUnit: 'indexed',
        annualUnit: '/ yr',
        eventsUnit: 'events',
        publicEventsPrefix: 'public events since',
        inUseUnit: 'in use',
        repositoriesUnit: 'repos',
        starPrefix: '★',
      },
    },
    observatory: {
      eyebrow: 'Test signal array',
      headline: 'Test observatory',
      statement: 'Test aggregate statement',
      impactLabel: 'Test impact',
      presenceLabel: 'Test presence',
      analyticsLabel: 'Test audience',
      discoveryLabel: 'Test discovery',
      windowLabel: 'Test window',
      baselineLabel: 'Test baseline',
      liveLabel: 'Test live',
      checkedLabel: 'Test observed',
      syncLabel: 'Test synchronizing',
      emptyLabel: 'Test baseline recorded',
      partialLabel: 'Test partial',
      staleLabel: 'Test stale',
      unavailableLabel: 'Test unavailable',
      unconfiguredLabel: 'Test unconfigured',
      metrics: {
        activeUsers: 'Test active audience',
        sessions: 'Test sessions',
        views: 'Test views',
        clicks: 'Test arrivals',
        impressions: 'Test appearances',
        ctr: 'Test discovery rate',
        position: 'Test discovery position',
        followers: 'Test followers',
        repositories: 'Test systems',
        contributions: 'Test output',
      },
    },
    utilityRail: {
      links: [{ id: 'test-repo', url: 'https://example.com/repo', label: 'Test repo' }],
    },
    lostSignal: {
      eyebrow: 'Test void',
      headline: 'Test missing',
      statement: 'Test coordinate',
      actionLabel: 'Test return',
    },
    runtime: TEST_RUNTIME_PRESENTATION,
  },
}
