import type { RuntimePresentation } from '../features/components/substrate/kernel/api/presentation/presentationTypes'

export const TEST_RUNTIME_PRESENTATION: RuntimePresentation = {
  errorBoundary: {
    headline: 'Test interruption',
    message: 'Test retry message',
    retryLabel: 'Test retry',
  },
  layout: {
    skipLabel: 'Test skip',
    workspaces: {
      ingress: 'Test ingress workspace',
      nexus: 'Test nexus workspace',
      dossier: 'Test dossier workspace',
      missions: 'Test missions workspace',
      telemetry: 'Test telemetry workspace',
      lostSignal: 'Test missing workspace',
    },
  },
  navigation: {
    pendingLabel: 'Test array pending',
    arrayLabel: 'Test array',
    appearanceLabel: 'Test appearance',
    operationsLabel: 'Test operations',
    primaryLabel: 'Test primary',
    menu: {
      openLabel: 'Test open menu',
      closeLabel: 'Test close menu',
      openText: 'Test controls',
      closeText: 'Test close',
    },
    routes: {
      nexus: { index: '01', label: 'Test nexus', systemLabel: 'Test command' },
      dossier: { index: '02', label: 'Test dossier', systemLabel: 'Test record' },
      missions: { index: '03', label: 'Test missions', systemLabel: 'Test operations' },
      telemetry: { index: '04', label: 'Test telemetry', systemLabel: 'Test uplink' },
    },
  },
  archiveControl: {
    heading: 'Test archive',
    closeLabel: 'Test close archive',
    closeText: 'Test close',
    commandLabel: 'Test command',
    dialogLabel: 'Test dialog',
    openLabel: 'Test open archive',
    triggerLabel: 'Test archive trigger',
    initialLines: ['Test archive ready'],
    placeholders: { neon: 'Test neon', mirage: 'Test mirage' },
    feedStates: {
      idle: 'IDLE',
      sync: 'SYNC',
      live: 'LIVE',
      stale: 'STALE',
      partial: 'DEGRADED',
      offline: 'OFFLINE',
    },
    commands: {
      help: ['Test help'],
      noData: 'Test no data',
      noCommits: 'Test no commits',
      noRepositoriesPrefix: 'Test no repositories ',
      noRepositoriesSuffix: '',
      labels: {
        designation: 'designation',
        origin: 'origin',
        incept: 'incept',
        units: 'units',
        output: 'output',
        feed: 'feed',
        repositories: 'repositories',
        commits: 'commits',
      },
      undisclosed: 'undisclosed',
      unknown: 'unknown',
      repositoryUnit: 'repositories',
      contributionUnit: 'contributions',
      themeCycled: 'Test cycled',
      themeSetPrefix: 'Test theme ',
      themeSetSuffix: '',
      unknownThemePrefix: 'Test unknown ',
      unknownThemeMiddle: ' test available ',
      commandUnavailable: 'Test unavailable',
      openingPrefix: 'Test opening ',
      openingSuffix: '',
      navigationUsage: 'Test navigation usage',
      unknownCommandPrefix: 'Test unknown command ',
      unknownCommandSuffix: '',
    },
  },
  theme: {
    prefixLabel: 'Test theme',
    downloadLabel: 'Test download',
    loadLabel: 'Test load',
    updateLabel: 'Test update',
    customLabel: 'Test custom',
    feedback: {
      importing: 'Test importing',
      ready: 'Test ready',
      exporting: 'Test exporting',
      failed: 'Test failed',
    },
  },
  sound: {
    enabledText: 'Test sound on',
    disabledText: 'Test sound off',
    enableLabel: 'Test enable sound',
    disableLabel: 'Test disable sound',
  },
  dossier: {
    eyebrow: 'Test dossier eyebrow',
    evidenceLabel: 'Test evidence',
    languageRangeLabel: 'Test language range',
    principlesLabel: 'Test principles',
    stats: {
      years: 'Test years',
      repositories: 'Test repositories',
      languages: 'Test languages',
      contributions: 'Test contributions',
    },
    meters: { languages: 'Test in use', principles: 'Test rules' },
    records: {
      capabilities: 'Test capabilities',
      capabilitiesEmpty: 'Test no capabilities',
      protocols: 'Test protocols',
      protocolsEmpty: 'Test no protocols',
    },
    unitPlate: {
      heading: 'Test unit record',
      status: 'Test operational',
      traceLabel: 'Test annual signal',
      traceAccessibilityPrefix: 'Test annual contribution trace:',
      undisclosed: 'Test undisclosed',
      recordSuffix: 'Test record',
      rows: {
        designation: 'Test designation',
        class: 'Test class',
        incept: 'Test incept',
        origin: 'Test origin',
        operators: 'Test operators',
        primarySystems: 'Test systems',
      },
    },
  },
  signalLattice: {
    headlineSuffix: 'Test contributions',
    accessibilityPrefix: 'Test calendar',
    lessLabel: 'Test less',
    moreLabel: 'Test more',
    levelLabel: 'Test level',
    months: [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ],
    weekdays: ['Mon', 'Wed', 'Fri'],
  },
  telemetry: {
    eyebrow: 'Test diagnostics',
    statement: 'Test live diagnostic statement',
    panels: {
      uplink: 'Test uplink',
      payload: 'Test payload',
      theme: 'Test theme',
      runtime: 'Test runtime',
    },
    latencyUnit: 'ms',
    emptyLabel: 'Test no telemetry',
    sourceLabel: 'Test source',
    labels: {
      repositories: 'repositories',
      operators: 'operators',
      languages: 'languages',
      contributions: 'contributions / yr',
      recordBegins: 'record begins',
      active: 'active',
      discovery: 'discovery',
      available: 'available',
      api: 'api.sdin.dev',
      contentFeed: 'content feed',
      githubSync: 'github sync',
      service: 'service',
      authoredData: 'authored data',
      brand: 'brand',
      store: 'store',
      actionsObserved: 'actions observed',
      lastAction: 'last action',
      reducedMotion: 'reduced motion',
      viewport: 'viewport',
      feed: 'GH + GOOGLE LIVE',
      theme: 'theme',
    },
    values: {
      timing: 'timing…',
      probing: 'probing…',
      keys: 'keys',
      units: 'units',
      loaded: 'loaded',
      actions: 'actions',
      store: '6 slices · rtk query',
      noneYet: 'none yet',
      respected: 'respected',
      notRequested: 'not requested',
      network: 'live from API',
      stale: 'stale · reconnecting',
      syncing: 'syncing',
      unavailable: 'API data unavailable',
      reachable: 'reachable',
      unreachable: 'unreachable',
      refreshing: 'refreshing…',
      fetching: 'fetching…',
      aggregated: 'aggregated',
      noData: 'no data',
      loading: 'Loading',
      error: 'Error',
      connected: 'Connected',
      offline: 'OFFLINE',
      sync: 'SYNC',
      refresh: 'REFRESH',
      idle: 'IDLE',
      live: 'LIVE',
      staleUpper: 'STALE',
    },
    overall: {
      nominal: 'Test nominal',
      syncing: 'Test syncing',
      degraded: 'Test degraded',
    },
    deck: {
      heading: 'Test telemetry',
      api: 'Test API',
      theme: 'Test theme',
      brand: 'Test brand',
    },
  },
}
