import { withAlpha } from './themeColorMath'
import { themeProfiles } from './themeProfiles'
import {
  BUILT_IN_THEME_IDS,
  CUSTOM_THEME_ID,
  type BuiltInThemeId,
  type ThemeProfile,
} from './themeTypes'

export const THEME_CSS_VARIABLES = [
  '--theme-label',
  '--background-color',
  '--surface-color',
  '--surface-raised-color',
  '--overlay-color',
  '--foreground-color',
  '--text-color',
  '--muted-color',
  '--muted-text-color',
  '--muted-ui-color',
  '--border-color',
  '--border-alpha-30',
  '--border-alpha-72',
  '--control-border-color',
  '--accent-color',
  '--accent-alpha-04',
  '--accent-alpha-05',
  '--accent-alpha-09',
  '--accent-alpha-13',
  '--accent-alpha-22',
  '--accent-alpha-38',
  '--accent-foreground-color',
  '--link-color',
  '--link-hover-color',
  '--selection-background',
  '--selection-color',
  '--line-highlight-color',
  '--gutter-color',
  '--focus-color',
  '--control-background-color',
  '--control-hover-background-color',
  '--control-foreground-color',
  '--error-color',
  '--error-text-color',
  '--warning-color',
  '--warning-text-color',
  '--success-color',
  '--success-text-color',
  '--info-color',
  '--info-text-color',
  '--signal-color',
  '--danger-color',
  '--tag-color',
  '--function-color',
  '--entity-color',
  '--string-color',
  '--regexp-color',
  '--markup-color',
  '--keyword-color',
  '--special-color',
  '--comment-color',
  '--constant-color',
  '--operator-color',
  '--contribution-step-0',
  '--contribution-step-1',
  '--contribution-step-2',
  '--contribution-step-3',
  '--contribution-step-4',
  '--visualization-axis-color',
  '--card-background',
  '--theme-icon',
  '--fx-opacity',
] as const

export type ThemeCssVariable = (typeof THEME_CSS_VARIABLES)[number]

export const toCssVariables = (
  profile: ThemeProfile
): Readonly<Record<ThemeCssVariable, string>> => ({
  '--theme-label': `"${profile.label}"`,
  '--background-color': profile.roles.background,
  '--surface-color': profile.roles.surface,
  '--surface-raised-color': profile.roles.surfaceRaised,
  '--overlay-color': profile.roles.overlay,
  '--foreground-color': profile.roles.foreground,
  '--text-color': profile.roles.foreground,
  '--muted-color': profile.roles.mutedText,
  '--muted-text-color': profile.roles.mutedText,
  '--muted-ui-color': profile.roles.muted,
  '--border-color': profile.roles.border,
  '--border-alpha-30': withAlpha(profile.roles.border, 0.3),
  '--border-alpha-72': withAlpha(profile.roles.border, 0.72),
  '--control-border-color': profile.roles.controlBorder,
  '--accent-color': profile.roles.accent,
  '--accent-alpha-04': withAlpha(profile.roles.accent, 0.04),
  '--accent-alpha-05': withAlpha(profile.roles.accent, 0.05),
  '--accent-alpha-09': withAlpha(profile.roles.accent, 0.09),
  '--accent-alpha-13': withAlpha(profile.roles.accent, 0.13),
  '--accent-alpha-22': withAlpha(profile.roles.accent, 0.22),
  '--accent-alpha-38': withAlpha(profile.roles.accent, 0.38),
  '--accent-foreground-color': profile.roles.accentForeground,
  '--link-color': profile.roles.link,
  '--link-hover-color': profile.roles.linkHover,
  '--selection-background': profile.roles.selection,
  '--selection-color': profile.roles.selection,
  '--line-highlight-color': profile.roles.lineHighlight,
  '--gutter-color': profile.roles.gutter,
  '--focus-color': profile.roles.focus,
  '--control-background-color': profile.roles.controlBackground,
  '--control-hover-background-color': profile.roles.controlBackgroundHover,
  '--control-foreground-color': profile.roles.controlForeground,
  '--error-color': profile.roles.danger,
  '--error-text-color': profile.roles.dangerText,
  '--warning-color': profile.roles.warning,
  '--warning-text-color': profile.roles.warningText,
  '--success-color': profile.roles.success,
  '--success-text-color': profile.roles.successText,
  '--info-color': profile.roles.info,
  '--info-text-color': profile.roles.infoText,
  '--signal-color': profile.roles.accent,
  '--danger-color': profile.roles.danger,
  '--tag-color': profile.syntax.tag,
  '--function-color': profile.syntax.function,
  '--entity-color': profile.syntax.entity,
  '--string-color': profile.syntax.string,
  '--regexp-color': profile.syntax.regexp,
  '--markup-color': profile.syntax.markup,
  '--keyword-color': profile.syntax.keyword,
  '--special-color': profile.syntax.special,
  '--comment-color': profile.syntax.comment,
  '--constant-color': profile.syntax.constant,
  '--operator-color': profile.syntax.operator,
  '--contribution-step-0': profile.visualization.contributionRamp[0],
  '--contribution-step-1': profile.visualization.contributionRamp[1],
  '--contribution-step-2': profile.visualization.contributionRamp[2],
  '--contribution-step-3': profile.visualization.contributionRamp[3],
  '--contribution-step-4': profile.visualization.contributionRamp[4],
  '--visualization-axis-color': profile.visualization.axisInk,
  '--card-background': profile.roles.surface,
  '--theme-icon': profile.icon,
  '--fx-opacity': profile.effects.opacity,
})

export const toTamaguiTheme = (profile: ThemeProfile) => ({
  background: profile.roles.background,
  backgroundHover: profile.roles.surface,
  backgroundPress: profile.roles.surfaceRaised,
  backgroundFocus: profile.roles.surface,
  color: profile.roles.foreground,
  colorHover: profile.roles.foreground,
  colorPress: profile.roles.foreground,
  colorFocus: profile.roles.foreground,
  borderColor: profile.roles.border,
  borderColorHover: profile.roles.accent,
  borderColorPress: profile.roles.accent,
  borderColorFocus: profile.roles.focus,
  placeholderColor: profile.roles.mutedText,
  gray5: profile.roles.muted,
  accent: profile.roles.accent,
  accentForeground: profile.roles.accentForeground,
  surface: profile.roles.surface,
  surfaceRaised: profile.roles.surfaceRaised,
  overlay: profile.roles.overlay,
  controlBorder: profile.roles.controlBorder,
  link: profile.roles.link,
  linkHover: profile.roles.linkHover,
  selection: profile.roles.selection,
  focus: profile.roles.focus,
  controlBackground: profile.roles.controlBackground,
  controlBackgroundHover: profile.roles.controlBackgroundHover,
  controlForeground: profile.roles.controlForeground,
  danger: profile.roles.danger,
  dangerText: profile.roles.dangerText,
  warning: profile.roles.warning,
  warningText: profile.roles.warningText,
  success: profile.roles.success,
  successText: profile.roles.successText,
  info: profile.roles.info,
  infoText: profile.roles.infoText,
  contribution0: profile.visualization.contributionRamp[0],
  contribution1: profile.visualization.contributionRamp[1],
  contribution2: profile.visualization.contributionRamp[2],
  contribution3: profile.visualization.contributionRamp[3],
  contribution4: profile.visualization.contributionRamp[4],
  axisInk: profile.visualization.axisInk,
  tag: profile.syntax.tag,
  function: profile.syntax.function,
  entity: profile.syntax.entity,
  string: profile.syntax.string,
  regexp: profile.syntax.regexp,
  markup: profile.syntax.markup,
  keyword: profile.syntax.keyword,
  special: profile.syntax.special,
  comment: profile.syntax.comment,
  constant: profile.syntax.constant,
  operator: profile.syntax.operator,
})

const customVariable = (name: ThemeCssVariable): string => `var(${name})`

export const customTamaguiTheme = {
  background: customVariable('--background-color'),
  backgroundHover: customVariable('--surface-color'),
  backgroundPress: customVariable('--surface-raised-color'),
  backgroundFocus: customVariable('--surface-color'),
  color: customVariable('--foreground-color'),
  colorHover: customVariable('--foreground-color'),
  colorPress: customVariable('--foreground-color'),
  colorFocus: customVariable('--foreground-color'),
  borderColor: customVariable('--border-color'),
  borderColorHover: customVariable('--accent-color'),
  borderColorPress: customVariable('--accent-color'),
  borderColorFocus: customVariable('--focus-color'),
  placeholderColor: customVariable('--muted-text-color'),
  gray5: customVariable('--muted-ui-color'),
  accent: customVariable('--accent-color'),
  accentForeground: customVariable('--accent-foreground-color'),
  surface: customVariable('--surface-color'),
  surfaceRaised: customVariable('--surface-raised-color'),
  overlay: customVariable('--overlay-color'),
  controlBorder: customVariable('--control-border-color'),
  link: customVariable('--link-color'),
  linkHover: customVariable('--link-hover-color'),
  selection: customVariable('--selection-background'),
  focus: customVariable('--focus-color'),
  controlBackground: customVariable('--control-background-color'),
  controlBackgroundHover: customVariable('--control-hover-background-color'),
  controlForeground: customVariable('--control-foreground-color'),
  danger: customVariable('--danger-color'),
  dangerText: customVariable('--error-text-color'),
  warning: customVariable('--warning-color'),
  warningText: customVariable('--warning-text-color'),
  success: customVariable('--success-color'),
  successText: customVariable('--success-text-color'),
  info: customVariable('--info-color'),
  infoText: customVariable('--info-text-color'),
  contribution0: customVariable('--contribution-step-0'),
  contribution1: customVariable('--contribution-step-1'),
  contribution2: customVariable('--contribution-step-2'),
  contribution3: customVariable('--contribution-step-3'),
  contribution4: customVariable('--contribution-step-4'),
  axisInk: customVariable('--visualization-axis-color'),
  tag: customVariable('--tag-color'),
  function: customVariable('--function-color'),
  entity: customVariable('--entity-color'),
  string: customVariable('--string-color'),
  regexp: customVariable('--regexp-color'),
  markup: customVariable('--markup-color'),
  keyword: customVariable('--keyword-color'),
  special: customVariable('--special-color'),
  comment: customVariable('--comment-color'),
  constant: customVariable('--constant-color'),
  operator: customVariable('--operator-color'),
}

const projectBuiltInThemes = <T>(project: (profile: ThemeProfile) => T) =>
  Object.fromEntries(
    BUILT_IN_THEME_IDS.map((id) => [id, project(themeProfiles[id])])
  ) as Record<BuiltInThemeId, T>

export const tamaguiThemes = {
  ...projectBuiltInThemes(toTamaguiTheme),
  [CUSTOM_THEME_ID]: customTamaguiTheme,
}
